### ISSUE TITLE
Not enough money error

### ISSUE THREAD

**Issue by valentinilas** [tagion/core-playnet#7]
Tested with 10 nodes running
[logs.zip](https://github.com/tagion/core-playnet/files/8980016/logs.zip)

Start: Both wallets have 100k

Steps Taken:

Transaction 1 - 10.000 transfer, from wallet 2 to wallet 1
After transaction:
Wallet1: 110.000
Wallet2: 89947.5

Transaction 1 - 10.000 transfer, from wallet 2 to wallet 1
After transaction:
Wallet1: 120.000
Wallet2: 79895.0

Transaction 3 - 5.000 transfer, from wallet 2 to wallet 1
After transaction:
Wallet1: 125.000
Wallet2: 74842.5

Transaction 4 - 5000 transfer, from wallet 1 to wallet 2 
[ERROR] When trying to pay. Worked when I ran the command again.
![Screenshot 2022-06-24 205755](https://user-images.githubusercontent.com/24529514/175648223-870ac625-3782-479b-ac3b-90dcd4d2942a.jpg)
After transaction:
Wallet1: 79842.5
Wallet2: 119947.5

Transaction 5 - 10000 transfer, from wallet 2 to wallet 1 
**[ERROR] Payment Failed, not enough money*
![Screenshot 2022-06-24 205934](https://user-images.githubusercontent.com/24529514/175648413-08c8233f-703a-4bfe-8060-34bb56a54cf4.jpg)

**Comment by alexSushko** [comment]
I guess it's a problem with the bill locking mechanism. 
Under the hood there's no account as such, there's a set of bills. If you want to pay twice in short period of time (before epoch happens) you need to use different bills to pay from. That's why we lock bill in a wallet, so next payment should use another bill. But if payment failed - we should not lock a bill or we should have a way to unlock a bill. 
I think fine approach now is to have a flag to unlock all bills. Plus a balance should be splited on locked and available.

**Comment by alexSushko** [comment]
Check new release - 0.9.1 
New flag in wallet should fix it
```
tagionwallet --unlock 
```
